env:
    browser: true
    es2021: true
    node: true
    jest/globals: true
root: true
extends:
    - 'eslint:recommended'
    - 'plugin:jest/recommended'
    - 'plugin:import/recommended'
    - 'plugin:prettier/recommended'
    - airbnb-base
    - prettier
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - import
    - jest
    - prettier
rules:
    no-use-before-define: error
    prefer-const: error
    no-multiple-empty-lines: error
    space-in-parens: error
    no-multi-spaces: error
    no-var: error
    semi: error
    indent: [error]
    no-console: off
    linebreak-style: 0
    no-param-reassign: 0
    prefer-destructuring: 0
    no-restricted-syntax: 0
    no-continue: off
    prettier/prettier: [error, {singleQuote: true, printWidth: 120, endOfLine: auto}]
    max-len: [error, {comments: 120, code: 120}]
    import/extensions: [error, ignorePackages, {js: always}]
    no-underscore-dangle: [2, {allow: [__filename, __dirname]}]
